imports:
    - node


filter:
    excluded_paths: [test/*, public/*]



build:
    nodes:
        my-test:
            environment:
                node:
                    version: 16.13.0

            
        # Install dependencies with npm
        dependencies:
            override:
                - npm install


        # run test and coverage
        tests:
            override:
                - 
                    command: npm run test
                    coverage:
                        file: coverage/clover.xml
                        format: clover

            
        # Use a cache to speed up builds
        cache:
            directories:
                - node_modules
            key:
                files:
                    - package-lock.json
