checks:
    javascript: true

filter:
    excluded_paths: [test/*, public/*]


build:
    environment:
        node: 16.13.0

    nodes:

        # Use a cache to speed up builds
        modules:
            cache:
                directories:
                    - node_modules

        analysis:
            tests:
                override:
                    - js-scrutinizer-run


        # run test and coverage
        test-coverage:
            tests:
                before:
                    - npm install

                override:
                    - command: npm run test
                      coverage:
                        file: "coverage/clover.xml"
                        format: "clover"
