version: 2.1

jobs:
    build:
        docker:
        # specify the version you desire here
        - image: circleci/node:16

    
        working_directory: ~/repo

        steps:
            - checkout

            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-

            - run:
                name: Install project dependencies
                command: npm install


            # Cache local dependencies if they don't exist
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}


            - run:
                name: run eslint and test
                command: |
                    npm run lint
                    npm run test
